config/routes.rb
Rails.application.routes.draw do
resources :murids
resources :bukus
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buku.rb
class Buku < ApplicationRecord
end

app/models/murid.rb
class Murid < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bukus_controller.rb
class BukusController < ApplicationController
  def new
    @buku = Buku.new
  end

  def create
    buku = Buku.new(resource_params)
    buku.save
    flash[:notice] = "buku has been created"
  end

  def edit
    @buku = Buku.find(params[:id])
  end

  def update
    @buku = Buku.find(params[:id])
    @buku.update(resource_params)
    flash[:notice] = "buku has been Updated"
    redirect_to bukus_path(@buku)
  end

  def destroy
    @buku = Buku.find(params[:id])
    @buku.destroy
    flash[:notice] = "buku has been Deleted"
    redirect_to bukus_path
  end

  def index
    @bukus = Buku.all
  end

  def show
    id = params[:id]
    @buku = Buku.find(id)
  end

  private
  def resource_params
    params.require(:buku).permit(:titlr, :page, :price, :description)
  end
end

app/controllers/murids_controller.rb
class MuridsController < ApplicationController
  def new
    @murid = Murid.new
  end

  def create
    murid = Murid.new(resource_params)
    murid.save
    flash[:notice] = "murid has been created"
  end

  def edit
    @murid = Murid.find(params[:id])
  end

  def update
    @murid = Murid.find(params[:id])
    @murid.update(resource_params)
    flash[:notice] = "murid has been Updated"
    redirect_to murids_path(@murid)
  end

  def destroy
    @murid = Murid.find(params[:id])
    @murid.destroy
    flash[:notice] = "murid has been Deleted"
    redirect_to murids_path
  end

  def index
    @murids = Murid.all
  end

  def show
    id = params[:id]
    @murid = Murid.find(id)
  end

  private
  def resource_params
    params.require(:murid).permit(:nama, :integer, :alamat)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bukus_helper.rb
module BukusHelper
end

app/helpers/murids_helper.rb
module MuridsHelper
end

app/views/bukus/edit.html.erb
<%= form_for(@buku) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>

    <%= f.label :name %> </br>
    <%= f.text_field :name %> </br>

    <%= f.label :page %> </br>
    <%= f.text_field :page %> </br>

    <%= f.submit  %> </br>
   
<% end %>

app/views/bukus/index.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

<table border="1" class="table table-dark">
    <tr align = "center">
        <td >Title</td>
        <td>Name</td>
        <td>Page</td>
        <td>Action</td>
    </tr>
    <% @bukus.each do |buku| %>
    <tr>
      <td><%= buku.title %></td>
       <td><%= buku.name %></td>
       <td><%= buku.page %></td>
       <td><%= link_to 'Detail', buku_path(buku) %>
        | <%= link_to 'Edit', edit_buku_path(buku) %> 
        | <%= link_to 'Delete', buku_path(buku), method: :delete, data: {confirm: 'are you sure?'}%></td> 
    </tr>
    <% end %>
</table>

<%= link_to "New Buku", new_buku_path %>

app/views/bukus/new.html.erb
<%= form_for(@buku) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>

    <%= f.label :name %> </br>
    <%= f.text_field :name %> </br>

    <%= f.label :page %> </br>
    <%= f.text_field :page %> </br> </br>

    <%= f.submit "Save" %> </br>
   
<% end %>

app/views/bukus/show.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

Title : <%= @buku.title %> </br>
Name : <%= @buku.name %> </br>
Page : <%= @buku.page %> </br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/murids/edit.html.erb
<%= form_for(@murid) do |f| %>
    <%= f.label :nama %> </br>
    <%= f.text_field :nama %> </br>

    <%= f.label :nis %> </br>
    <%= f.text_field :nis %> </br>

    <%= f.label :alamat %> </br>
    <%= f.text_field :alamat %> </br>

    <%= f.submit  %> </br>
   
<% end %>

app/views/murids/index.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

<table border="1" class="table table-dark">
    <tr align = "center">
        <td >Nama</td>
        <td>Nis</td>
        <td>Alamat</td>
        <td>Action</td>
    </tr>
    <% @murids.each do |murid| %>
    <tr>
      <td><%= murid.nama %></td>
       <td><%= murid.nis %></td>
       <td><%= murid.alamat %></td>
       <td><%= link_to 'Detail', murid_path(murid) %>
        | <%= link_to 'Edit', edit_murid_path(murid) %> 
        | <%= link_to 'Delete', murid_path(murid), method: :delete, data: {confirm: 'are you sure?'}%></td> 
    </tr>
    <% end %>
</table>

<%= link_to "New murid", new_murid_path %>

app/views/murids/new.html.erb
<%= form_for(@murid) do |f| %>
    <%= f.label :nama %> </br>
    <%= f.text_field :nama %> </br>

    <%= f.label :nis %> </br>
    <%= f.text_field :nis %> </br>

    <%= f.label :alamat %> </br>
    <%= f.text_field :alamat %> </br> </br>

    <%= f.submit "Save" %> </br>
   
<% end %>

app/views/murids/show.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

Nama : <%= @buku.nama %> </br>
Nis : <%= @buku.nis %> </br>
Alamat : <%= @buku.alamat %> </br>